@startuml Manage Reservation (GET ALL)

header Sample MassageCenter Sequence Diagram
footer Page %page% of %lastpage%
title "Manage Reservation (GET ALL)"

participant "Client" as client
participant "<<javaScript>>\n:server" as server
participant "<<router>>\n:Reservation" as routerReservation
participant "<<controllers>>\n:Reservation" as controllersReservation
participant "<<model>>\n:Reservation" as modelMassageShop
database "<<MongoDB>>\n:Reservation" as ReservationsDatabase

client->server ++:req.get('/Reservation')
server->routerReservation ++:app.use('/Reservation',massageShops)
routerMassageShops -> controllersMassageShops ++:getMassageShops()
alt req.user.role = admin
  controllersReservation->modelReservation ++: find()
else req.user.role = user
  controllersReservation->modelReservation ++: findById(req.params.id)
end

alt Reservation exists
  modelReservation ->ReservationDatabase ++: ReservationSchema
  ReservationDatabase --> modelReservation --: Reservation
  controllersReservation <-- modelReservation --: Reservation
  controllersReservation->client --: res.status(200)
else Reservation does not exist
  controllersReservation->client --: res.status(500)
end

@enduml
