@startuml addReservations (POST)

header Sample MassageShopReservation Sequence Diagram
footer Page %page% of %lastpage%
title "Create Reservation (POST)"

participant "Client" as client
participant "<<javaScript>>\n:server" as server
participant "<<router>>\n:reservations" as routerReservation
participant "<<controllers>>\n:reservations" as controllersReservation
participant "<<model>>\n:Reservation" as modelReservation
database "<<MongoDB>>\n:reservations" as ReservationDatabase


client->server ++:req.post('/api/v1/massageShops/:massageShopId/reservations')
server->routerReservation ++:app.use('/reservations', reservations)
routerReservation -> controllersReservation ++: addReservations(req, res, next)
controllersReservation->modelReservation ++: create(resDate: req.body.resDate, user: req.body.user, massageShop: req.body.massageShop)

alt reservations made successfully
 modelReservation ->ReservationDatabase ++: ReservationSchema
  ReservationDatabase --> modelReservation --: reservations
  controllersReservation <-- modelReservation --: reservations
  controllersReservation->client --: res.status(201).json({success: true, data: reservation})
else error in making rent
  controllersReservation->client --: res.status(500).json({ success: false })
end
@enduml