@startuml Massage Reservation System Use Case Diagram
left to right direction
actor "User" as user
rectangle "Massage Reservation System" as massageReservationSystem {    
    usecase "Register" as register
    usecase "View\nMassageShops" as viewMassageShops
    usecase "Manage\nReservation" as manageRes
    usecase "Manage\nMassageShop" as manageMassageShop
}

user -- register
user -- viewMassageShops
user -- manageRes

actor "Admin" as admin
register -- admin
manageMassageShop -- admin
manageRes -- admin

@enduml